name: lint

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1

      - name: Install Dependencies
        run: yarn install

      - name: Build check
        run: yarn run --silent build

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1

      - name: Setup problemMatcher
        run: echo "::add-matcher::.github/tslint-stylish.json"

      - name: Install Dependencies
        run: yarn install

      - name: Lint check
        run: yarn run --silent lint --format stylish
